"""
Spin up a new client site from the Kai Finds template.

Steps:
  1. Copy ../../kai/ to ../../<slug>/
  2. Write a config_overrides.json so the brother can edit values later
  3. Parse the provided spreadsheet → static/products.json (if URL given)
  4. Generate placeholder favicon + .env.example
  5. (Optional) git init + push to GitHub via gh CLI
  6. (Optional) create Render service via Render API

Usage:
    python create_site.py --slug acmefinds --name "Acme Finds" \
        --agent KakoBuy --affcode acme --color "#06b6d4" \
        [--spreadsheet https://docs.google.com/...] \
        [--push] [--deploy] [--pixel 123456]

You can also run with no flags and it will prompt for everything.
"""
import os
import sys
import json
import shutil
import argparse
import subprocess
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent  # C:\Users\talan\clients
TEMPLATE = ROOT / 'kai'
SCRIPTS = Path(__file__).resolve().parent

AGENT_PRESETS = {
    'kakobuy':    {'domain': 'kakobuy.com',    'signup': 'https://www.kakobuy.com/register?affcode={aff}',     'product': 'https://www.kakobuy.com/item/details'},
    'joyagoo':    {'domain': 'joyagoo.com',    'signup': 'https://www.joyagoo.com/signup?inviteCode={aff}',     'product': 'https://www.joyagoo.com/product'},
    'cnfans':     {'domain': 'cnfans.com',     'signup': 'https://cnfans.com/register?ref={aff}',              'product': 'https://cnfans.com/product'},
    'sugargoo':   {'domain': 'sugargoo.com',   'signup': 'https://www.sugargoo.com/index/user/register.html?invitcode={aff}', 'product': 'https://www.sugargoo.com/index/item/index'},
    'oopbuy':     {'domain': 'oopbuy.com',     'signup': 'https://oopbuy.com/register?invitcode={aff}',         'product': 'https://oopbuy.com/product/details'},
    'allchinabuy':{'domain': 'allchinabuy.com','signup': 'https://www.allchinabuy.com/en/page/login/#/registered?partnercode={aff}', 'product': 'https://www.allchinabuy.com/en/page/buy/'},
    'mulebuy':    {'domain': 'mulebuy.com',    'signup': 'https://mulebuy.com/register?affcode={aff}',          'product': 'https://mulebuy.com/product/details'},
    'hoobuy':     {'domain': 'hoobuy.com',     'signup': 'https://hoobuy.com/?utm_source={aff}',                'product': 'https://hoobuy.com/product/0'},
}


def shade(hex_color, pct=-15):
    """Darken or lighten a hex color."""
    h = hex_color.lstrip('#')
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    f = (100 + pct) / 100
    r = max(0, min(255, int(r * f)))
    g = max(0, min(255, int(g * f)))
    b = max(0, min(255, int(b * f)))
    return f'#{r:02x}{g:02x}{b:02x}'


def copy_template(slug):
    dest = ROOT / slug
    if dest.exists():
        raise SystemExit(f'Folder already exists: {dest}')
    print(f'Copying template {TEMPLATE} → {dest}')
    shutil.copytree(TEMPLATE, dest, ignore=shutil.ignore_patterns(
        '__pycache__', '*.pyc', 'data', '.env', 'analytics.db', '*.db'))
    (dest / 'data').mkdir(exist_ok=True)
    return dest


def write_favicon(dest, name, color):
    """Generate a simple favicon with the first letter of the brand."""
    letter = name.strip()[0].upper()
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none">
  <rect width="64" height="64" rx="14" fill="{color}"/>
  <text x="32" y="44" font-family="Arial Black, sans-serif" font-size="34" font-weight="900" fill="#000" text-anchor="middle">{letter}</text>
</svg>
'''
    (dest / 'static' / 'favicon.svg').write_text(svg, encoding='utf-8')
    print(f'  ✓ favicon.svg ({letter} on {color})')


def split_name(full):
    """Split 'Acme Finds' → ('Acme', 'Finds'). Fallback to (full, '')."""
    parts = full.strip().split(maxsplit=1)
    if len(parts) == 2:
        return parts[0], parts[1]
    # No space: split mid-word if long enough
    if len(full) > 5:
        mid = len(full) // 2
        return full[:mid], full[mid:]
    return full, ''


def write_config(dest, cfg):
    """Write config_overrides.json + .env.example so values can be edited later."""
    (dest / 'config_overrides.json').write_text(
        json.dumps(cfg, indent=2), encoding='utf-8')

    env = f'''# Generated by create_site.py — edit and copy to .env (or set in Render)
FLASK_ENV=production
SECRET_KEY={secrets.token_hex(32)}
ADMIN_PASSWORD={cfg.get("admin_password", "changeme123")}

SITE_NAME={cfg["name"]}
SITE_NAME_PART1={cfg["name_part1"]}
SITE_NAME_PART2={cfg["name_part2"]}
SITE_DOMAIN={cfg["domain"]}

AGENT_NAME={cfg["agent_name"]}
AGENT_DOMAIN={cfg["agent_domain"]}
AGENT_SIGNUP_URL={cfg["agent_signup_url"]}
AGENT_PRODUCT_URL={cfg["agent_product_url"]}
AFFILIATE_CODE={cfg["affiliate_code"]}

BRAND_COLOR={cfg["brand_color"]}
BRAND_COLOR_SHADOW={cfg["brand_color_shadow"]}
META_PIXEL_ID={cfg.get("meta_pixel_id", "")}
COUPON_AMOUNT={cfg.get("coupon_amount", "400")}
TAGLINE={cfg.get("tagline", "")}
DISCORD_URL={cfg.get("discord_url", "")}
'''
    (dest / '.env.example').write_text(env, encoding='utf-8')
    print('  ✓ .env.example + config_overrides.json')


def patch_app_defaults(dest, cfg):
    """Update SITE_CONFIG defaults in app.py so the site works even without env vars set."""
    app_py = dest / 'app.py'
    src = app_py.read_text(encoding='utf-8')
    pairs = [
        ("'SITE_NAME', 'Kai Finds'",                     f"'SITE_NAME', '{cfg['name']}'"),
        ("'SITE_NAME_PART1', 'Kai'",                     f"'SITE_NAME_PART1', '{cfg['name_part1']}'"),
        ("'SITE_NAME_PART2', 'Finds'",                   f"'SITE_NAME_PART2', '{cfg['name_part2']}'"),
        ("'SITE_DOMAIN', 'kaifinds.com'",                f"'SITE_DOMAIN', '{cfg['domain']}'"),
        ("'AGENT_NAME', 'KakoBuy'",                      f"'AGENT_NAME', '{cfg['agent_name']}'"),
        ("'AGENT_DOMAIN', 'kakobuy.com'",                f"'AGENT_DOMAIN', '{cfg['agent_domain']}'"),
        ("'https://www.kakobuy.com/register?affcode=kai'", f"'{cfg['agent_signup_url']}'"),
        ("'https://www.kakobuy.com/item/details'",       f"'{cfg['agent_product_url']}'"),
        ("'AFFILIATE_CODE', 'kai'",                      f"'AFFILIATE_CODE', '{cfg['affiliate_code']}'"),
        ("'BRAND_COLOR', '#06b6d4'",                     f"'BRAND_COLOR', '{cfg['brand_color']}'"),
        ("'BRAND_COLOR_SHADOW', '#0891b2'",              f"'BRAND_COLOR_SHADOW', '{cfg['brand_color_shadow']}'"),
    ]
    for old, new in pairs:
        if old in src:
            src = src.replace(old, new)
    app_py.write_text(src, encoding='utf-8')
    print('  ✓ app.py defaults patched')


def import_spreadsheet(dest, url, cny_rate=6.5):
    parser = SCRIPTS / 'parse_spreadsheet.py'
    out = dest / 'static' / 'products.json'
    print(f'\nImporting spreadsheet...')
    rc = subprocess.call([sys.executable, str(parser), url, str(out),
                          '--cny-rate', str(cny_rate)])
    if rc != 0:
        print(f'  ! parser exited with code {rc}; leaving placeholder products in place')


def git_push(dest, slug, github_user='Lude5'):
    repo = f'{github_user}/{slug}'
    print(f'\nCreating GitHub repo {repo}...')
    cmds = [
        ['git', 'init', '-b', 'main'],
        ['git', 'add', '.'],
        ['git', 'commit', '-m', 'Initial site from Kai Finds template'],
    ]
    for c in cmds:
        if subprocess.call(c, cwd=dest) != 0:
            print(f'  ! git command failed: {c}')
            return None
    # gh repo create handles remote + push
    rc = subprocess.call(['gh', 'repo', 'create', repo, '--private',
                          '--source', '.', '--remote', 'origin', '--push'],
                         cwd=dest)
    if rc != 0:
        print('  ! gh repo create failed')
        return None
    print(f'  ✓ pushed to https://github.com/{repo}')
    return repo


def render_deploy(slug, repo, cfg):
    """Create a Render web service via the Render API.
    Requires RENDER_API_KEY env var and RENDER_OWNER_ID env var.
    """
    api_key = os.environ.get('RENDER_API_KEY')
    owner_id = os.environ.get('RENDER_OWNER_ID')
    if not api_key or not owner_id:
        print('\n! RENDER_API_KEY or RENDER_OWNER_ID missing — skipping Render deploy.')
        print('  Set them and re-run with --deploy, or create the service manually.')
        return None

    import requests
    env_vars = [
        {'key': 'FLASK_ENV', 'value': 'production'},
        {'key': 'SECRET_KEY', 'value': secrets.token_hex(32)},
        {'key': 'ADMIN_PASSWORD', 'value': cfg.get('admin_password', 'changeme123')},
        {'key': 'SITE_NAME', 'value': cfg['name']},
        {'key': 'SITE_NAME_PART1', 'value': cfg['name_part1']},
        {'key': 'SITE_NAME_PART2', 'value': cfg['name_part2']},
        {'key': 'SITE_DOMAIN', 'value': cfg['domain']},
        {'key': 'AGENT_NAME', 'value': cfg['agent_name']},
        {'key': 'AGENT_DOMAIN', 'value': cfg['agent_domain']},
        {'key': 'AGENT_SIGNUP_URL', 'value': cfg['agent_signup_url']},
        {'key': 'AGENT_PRODUCT_URL', 'value': cfg['agent_product_url']},
        {'key': 'AFFILIATE_CODE', 'value': cfg['affiliate_code']},
        {'key': 'BRAND_COLOR', 'value': cfg['brand_color']},
        {'key': 'BRAND_COLOR_SHADOW', 'value': cfg['brand_color_shadow']},
        {'key': 'META_PIXEL_ID', 'value': cfg.get('meta_pixel_id', '')},
        {'key': 'DISCORD_URL', 'value': cfg.get('discord_url', '')},
    ]
    body = {
        'type': 'web_service',
        'name': slug,
        'ownerId': owner_id,
        'repo': f'https://github.com/{repo}',
        'branch': 'main',
        'autoDeploy': 'yes',
        'serviceDetails': {
            'env': 'python',
            'plan': 'starter',
            'region': 'oregon',
            'buildCommand': 'pip install -r requirements.txt',
            'startCommand': 'gunicorn app:app',
            'envSpecificDetails': {'pythonVersion': '3.11'},
        },
        'envVars': env_vars,
    }
    print(f'\nCreating Render service "{slug}"...')
    r = requests.post('https://api.render.com/v1/services',
                      headers={'Authorization': f'Bearer {api_key}',
                               'Content-Type': 'application/json'},
                      json=body, timeout=30)
    if r.status_code not in (200, 201):
        print(f'  ! Render API returned {r.status_code}: {r.text[:300]}')
        return None
    svc = r.json().get('service', r.json())
    sid = svc.get('id')
    url = f'https://{slug}.onrender.com'
    print(f'  ✓ Render service {sid}')
    print(f'  ✓ Live URL: {url} (first deploy takes ~5 min)')
    return url


def prompt(label, default=None):
    suffix = f' [{default}]' if default else ''
    v = input(f'{label}{suffix}: ').strip()
    return v or default


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--slug', help='Folder + repo name, lowercase, no spaces (e.g. acmefinds)')
    p.add_argument('--name', help='Display name (e.g. "Acme Finds")')
    p.add_argument('--domain', help='Public domain (e.g. acmefinds.com)')
    p.add_argument('--agent', help='Agent key: kakobuy/joyagoo/cnfans/sugargoo/oopbuy/allchinabuy/mulebuy/hoobuy')
    p.add_argument('--affcode', help='Affiliate code on the agent')
    p.add_argument('--color', default='#06b6d4', help='Brand hex color')
    p.add_argument('--pixel', default='', help='Meta Pixel ID')
    p.add_argument('--discord', default='', help='Discord invite URL (shown as floating side button)')
    p.add_argument('--spreadsheet', help='Google Sheets URL (optional)')
    p.add_argument('--cny-rate', type=float, default=6.5)
    p.add_argument('--admin-pass', default='', help='Admin panel password (default: random)')
    p.add_argument('--push', action='store_true', help='git init + create GitHub repo via gh')
    p.add_argument('--deploy', action='store_true', help='Create Render service (needs RENDER_API_KEY + RENDER_OWNER_ID)')
    args = p.parse_args()

    # Prompt for anything missing
    slug = args.slug or prompt('Site slug (lowercase, no spaces)')
    name = args.name or prompt('Display name', slug.title())
    domain = args.domain or prompt('Domain', f'{slug}.com')
    agent = (args.agent or prompt('Agent', 'kakobuy')).lower()
    affcode = args.affcode or prompt('Affiliate code', slug)
    color = args.color or prompt('Brand color hex', '#06b6d4')

    if agent not in AGENT_PRESETS:
        raise SystemExit(f'Unknown agent "{agent}". Known: {list(AGENT_PRESETS)}')
    preset = AGENT_PRESETS[agent]

    n1, n2 = split_name(name)
    cfg = {
        'name': name,
        'name_part1': n1,
        'name_part2': n2,
        'domain': domain,
        'agent_name': agent.title() if agent != 'kakobuy' else 'KakoBuy',
        'agent_domain': preset['domain'],
        'agent_signup_url': preset['signup'].format(aff=affcode),
        'agent_product_url': preset['product'],
        'affiliate_code': affcode,
        'brand_color': color,
        'brand_color_shadow': shade(color, -15),
        'meta_pixel_id': args.pixel,
        'discord_url': args.discord,
        'admin_password': args.admin_pass or secrets.token_urlsafe(12),
        'tagline': f'The best {agent.title()} finds. Lowest prices. Daily drops.',
    }

    print(f'\n=== Creating site "{name}" ({slug}) ===\n')
    dest = copy_template(slug)
    write_favicon(dest, name, color)
    write_config(dest, cfg)
    patch_app_defaults(dest, cfg)

    if args.spreadsheet:
        import_spreadsheet(dest, args.spreadsheet, args.cny_rate)
    else:
        print('\n(No spreadsheet given — placeholder products from Kai template will be used.)')

    repo = None
    if args.push:
        repo = git_push(dest, slug)

    if args.deploy:
        if not repo:
            print('\n! --deploy needs a GitHub repo. Re-run with --push too.')
        else:
            render_deploy(slug, repo, cfg)

    print(f'\n✓ Done.')
    print(f'  Folder:   {dest}')
    print(f'  Admin pw: {cfg["admin_password"]}')
    if not args.push:
        print(f'\nTo push later:')
        print(f'  cd "{dest}"')
        print(f'  python "{SCRIPTS / "create_site.py"}" --slug {slug} --push --deploy')
    print(f'\nRun locally:')
    print(f'  cd "{dest}" && python app.py')


if __name__ == '__main__':
    main()
